title: MARS | Marlborough's Academic Research Society
author: Marlborough's Academic Research Society

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex
    
html:
  home_page_in_navbar: false  