title: Eureka Journal
author: Marlborough School
logo: images/logoOption.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex
    
html:
  home_page_in_navbar: false  